---
title: "Practical Work I"
author: "Group 12.X, names:---"
date: \today
output:
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
  html_document:
    toc: no
    toc_depth: '4'
  word_document:
    toc: no
    toc_depth: '4'
geometry: left=1.9cm,right=1.9cm,top=1.25cm,bottom=1.52cm
fontsize: 18pt
subtitle: 'Data Mining 21-22 Q2'
classoption: a4paper
editor_options: 
  
  chunk_output_type: console
---

# Introduction
## Data Description
Variable description

...


## Load Required Packages

```{r paquets, message=FALSE, warning=FALSE}
# Clean workspace
rm(list=ls())

options(contrasts=c("contr.treatment","contr.treatment"))
requiredPackages <- c("effects","FactoMineR","car", "factoextra","RColorBrewer","ggplot2","dplyr","ggmap","ggthemes","knitr", "magrittr")
package.check <- lapply(requiredPackages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})
search()
```

## Some useful functions

```{r funcions}
# Some useful functions
calcQ <- function(x) {
  s.x <- summary(x)
  iqr<-s.x[5]-s.x[2]
  list(souti=s.x[2]-3*iqr, mouti=s.x[2]-1.5*iqr, min=s.x[1], q1=s.x[2], q2=s.x[3], 
       q3=s.x[5], max=s.x[6], mouts=s.x[5]+1.5*iqr, souts=s.x[5]+3*iqr ) }

countNA <- function(x) {
  mis_x <- NULL
  for (j in 1:ncol(x)) {mis_x[j] <- sum(is.na(x[,j])) }
  mis_x <- as.data.frame(mis_x)
  rownames(mis_x) <- names(x)
  mis_i <- rep(0,nrow(x))
  for (j in 1:ncol(x)) {mis_i <- mis_i + as.numeric(is.na(x[,j])) }
  list(mis_col=mis_x,mis_ind=mis_i) }

countX <- function(x,X) {
  n_x <- NULL
  for (j in 1:ncol(x)) {n_x[j] <- sum(x[,j]==X) }
  n_x <- as.data.frame(n_x)
  rownames(n_x) <- names(x)
  nx_i <- rep(0,nrow(x))
  for (j in 1:ncol(x)) {nx_i <- nx_i + as.numeric(x[,j]==X) }
  list(nx_col=n_x,nx_ind=nx_i) }
```

## Load data

Carreguem el dataset i definim el nostre directori de treball

```{r load}
#change working directory
setwd("D:/Drive/UNI/Q8/MD/archive")
library(readr)
df <- read_csv("train.csv")
summary(df)
```

# Initial analisys
 ... 

## Metadata description

```{r}

```

## Univariate descriptive statistics of raw variables

```{r}

```

## Preprocessing of variables

```{r}
names(df)
var_bin <- names(df)[c(2,4,6,18:20)]
summary(df[var_bin])
var_num <- names(df)[c(1,3,7:10,17)]
summary(df[var_num])
var_cat <- names(df)[c(5,11:16,21)]
summary(df[var_cat])
```

### Binary variables

```{r}
var_bin
df[,"blue"]
df$blue <- factor(df$blue, labels = c("NoBth","YesBth"))
summary(df$blue)

df[,"dual_sim"]
df$dual_sim <- factor(df$dual_sim, labels = c("No2Sim","Yes2Sim"))
summary(df$dual_sim)

df[,"four_g"]
df$four_g <- factor(df$four_g, labels = c("No4G","Yes4G"))
summary(df$four_g)

df[,"three_g"]
df$three_g <- factor(df$three_g, labels = c("No3G","Yes3G"))
summary(df$three_g)

df[,"touch_screen"]
df$touch_screen <- factor(df$touch_screen, labels = c("NoTouch","YesTouch"))
summary(df$touch_screen)

df[,"wifi"]
df$wifi <- factor(df$wifi, labels = c("NoWifi","YesWifi"))
summary(df$wifi)
```

No NA's

### 
